import SwiftUI

// MARK: - Icon Assets Extension
extension Image {
    static let allIconNames: [String] = [
        "3d-filled", "3d-outline", "3d-slash-filled", "3d-slash-outline",
        "accessibility-filled", "accessibility-outline", "account-switcher-filled", "account-switcher-outline",
        "acquaintances-filled", "acquaintances-outline", "activity-filled", "activity-outline", "ad-filled",
        "ad-outline", "airplane-filled", "airplane-outline", "airplay-filled", "airplay-outline",
        "alarm-clock-filled", "alarm-clock-outline", "allowlist-filled", "allowlist-outline", "anonymous-filled",
        "anonymous-outline", "aperture-filled", "aperture-outline", "app-audio-hub-filled", "app-audio-hub-outline",
        "app-business-suite-filled", "app-business-suite-outline", "app-discord-filled", "app-discord-outline",
        "app-facebook-account-center-outline", "app-facebook-admin-assist-filled", "app-facebook-admin-assist-outline",
        "app-facebook-avatars-filled", "app-facebook-avatars-outline", "app-facebook-circle-filled",
        "app-facebook-circle-lite-filled", "app-facebook-circle-lite-outline", "app-facebook-circle-outline",
        "app-facebook-dating-filled", "app-facebook-dating-outline", "app-facebook-family-filled",
        "app-facebook-family-outline", "app-facebook-gaming-filled", "app-facebook-gaming-outline",
        "app-facebook-groups-filled", "app-facebook-groups-outline", "app-facebook-highlights-filled",
        "app-facebook-highlights-outline", "app-facebook-news-filled", "app-facebook-news-outline",
        "app-facebook-nicknames-filled", "app-facebook-nicknames-outline", "app-facebook-pay-filled",
        "app-facebook-pay-outline", "app-facebook-reels", "app-facebook-reels-dashed-filled",
        "app-facebook-reels-dashed-outline", "app-facebook-reels-filled", "app-facebook-reels-outline",
        "app-family-center-filled", "app-family-center-outline", "app-groups-plus-filled", "app-groups-plus-outline",
        "app-hashtag-filled", "app-hashtag-outline", "app-horizon-filled", "app-horizon-outline",
        "app-imessage-filled", "app-imessage-outline", "app-imo-filled", "app-imo-outline",
        "app-instagram-edits-filled", "app-instagram-edits-outline", "app-instagram-filled", "app-instagram-outline",
        "app-instant-games-filled", "app-instant-games-outline", "app-kakao-filled", "app-kakao-outline",
        "app-kwai-filled", "app-kwai-outline", "app-line-filled", "app-line-outline", "app-linkedin-filled",
        "app-linkedin-outline", "app-mentions-filled", "app-mentions-outline", "app-messages-filled",
        "app-messages-outline", "app-messenger-filled", "app-messenger-outline", "app-messenger-plus-filled",
        "app-messenger-plus-outline", "app-messenger-swish-filled", "app-messenger-swish-outline",
        "app-meta-ai-characters-filled", "app-meta-ai-characters-outline", "app-meta-ai-filled", "app-meta-ai-outline",
        "app-meta-filled", "app-meta-outline", "app-metamate-filled", "app-metamate-outline",
        "app-pages-feed-filled", "app-pages-feed-outline", "app-pages-filled", "app-pages-outline",
        "app-paypal-filled", "app-paypal-outline", "app-pinterest-filled", "app-pinterest-outline",
        "app-podcasts-filled", "app-podcasts-outline", "app-reddit-filled", "app-reddit-outline",
        "app-rooms-filled", "app-rooms-outline", "app-screenshot-tests-filled", "app-screenshot-tests-outline",
        "app-snapchat-filled", "app-snapchat-outline", "app-soundbites-filled", "app-soundbites-outline",
        "app-soundcloud-filled", "app-soundcloud-outline", "app-spotify-filled", "app-spotify-outline",
        "app-telegram-filled", "app-telegram-outline", "app-threads-filled", "app-threads-outline",
        "app-tiktok-filled", "app-tiktok-outline", "app-twitch-filled", "app-twitch-outline",
        "app-twitter-filled", "app-twitter-outline", "app-viber-filled", "app-viber-outline",
        "app-wechat-filled", "app-wechat-outline", "app-whatsapp-business-filled", "app-whatsapp-business-outline",
        "app-whatsapp-filled", "app-whatsapp-outline", "app-whatsapp-status-filled", "app-whatsapp-status-outline",
        "app-whatsapp-status-plus-filled", "app-whatsapp-status-plus-outline", "app-workplace-chat-comment-filled",
        "app-workplace-chat-comment-outline", "app-workplace-chat-filled", "app-workplace-chat-outline",
        "app-workplace-filled", "app-workplace-outline", "app-youtube-filled", "app-youtube-outline",
        "apple-filled", "apple-outline", "apps-filled", "apps-outline", "armchair-filled", "armchair-outline",
        "arrow-bottom-tab-filled", "arrow-bottom-tab-outline", "arrow-curved-left-cross-filled",
        "arrow-curved-left-cross-outline", "arrow-curved-left-down-filled", "arrow-curved-left-down-outline",
        "arrow-curved-left-filled", "arrow-curved-left-outline", "arrow-curved-right-cross-filled",
        "arrow-curved-right-cross-outline", "arrow-curved-right-down-filled", "arrow-curved-right-down-outline",
        "arrow-curved-right-filled", "arrow-curved-right-outline", "arrow-diagonal-left-down-filled",
        "arrow-diagonal-left-down-outline", "arrow-diagonal-left-up-filled", "arrow-diagonal-left-up-outline",
        "arrow-diagonal-right-down-filled", "arrow-diagonal-right-down-outline", "arrow-diagonal-right-up-filled",
        "arrow-diagonal-right-up-outline", "arrow-down-circle-filled", "arrow-down-circle-outline",
        "arrow-down-filled", "arrow-down-outline", "arrow-left-circle-filled", "arrow-left-circle-outline",
        "arrow-left-filled", "arrow-left-outline", "arrow-move-filled", "arrow-move-outline",
        "arrow-right-circle-filled", "arrow-right-circle-outline", "arrow-right-filled", "arrow-right-outline",
        "arrow-up-circle-filled", "arrow-up-circle-outline", "arrow-up-filled", "arrow-up-outline",
        "arrows-circle-filled", "arrows-circle-outline", "arrows-demote-filled", "arrows-demote-outline",
        "arrows-left-right-circle-filled", "arrows-left-right-circle-outline", "arrows-left-right-filled",
        "arrows-left-right-outline", "arrows-promote-filled", "arrows-promote-outline", "arrows-right-left-filled",
        "arrows-right-left-outline", "arrows-square-add-filled", "arrows-square-add-outline",
        "arrows-up-down-circle-filled", "arrows-up-down-circle-outline", "arrows-up-down-dot-filled",
        "arrows-up-down-dot-outline", "arrows-up-down-filled", "arrows-up-down-outline", "article-filled",
        "article-outline", "arts-filled", "arts-outline", "aspect-ratio-filled", "aspect-ratio-outline",
        "asterisk-filled", "asterisk-outline", "at-sign-filled", "at-sign-outline", "audio-effects-filled",
        "audio-effects-outline", "audio-hi-filled", "audio-hi-outline", "audio-lo-filled", "audio-lo-outline",
        "audio-mid-filled", "audio-mid-outline", "audio-note-filled", "audio-note-outline", "audio-null-filled",
        "audio-null-outline", "audio-off-filled", "audio-off-outline", "audio-wave-filled", "audio-wave-outline",
        "automation-filled", "automation-outline", "avatar-editor-filled", "avatar-editor-outline",
        "backpack-filled", "backpack-outline", "backspace-filled", "backspace-outline", "badge-checkmark-filled",
        "badge-checkmark-outline", "badge-empty-filled", "badge-empty-outline", "badge-filled",
        "badge-heart-filled", "badge-heart-outline", "badge-outline", "badge-ribbon-checkmark-filled",
        "badge-ribbon-checkmark-outline", "badge-ribbon-filled", "badge-ribbon-outline", "badge-star-filled",
        "badge-star-outline", "balcony-filled", "balcony-outline", "balloon-filled", "balloon-outline",
        "bar-chart-filled", "bar-chart-outline", "bar-chart-star-filled", "bar-chart-star-outline",
        "bath-filled", "bath-outline", "beach-filled", "beach-outline", "beaker-filled", "beaker-outline",
        "bed-filled", "bed-outline", "beer-filled", "beer-outline", "bicycle-filled", "bicycle-outline",
        "binoculars-filled", "binoculars-outline", "bird-filled", "bird-outline", "blocklist-filled",
        "blocklist-outline", "bluetooth-filled", "bluetooth-outline", "bolt-circle-filled", "bolt-circle-outline",
        "bone-filled", "bone-outline", "book-filled", "book-outline", "bookmark-cross-filled",
        "bookmark-cross-outline", "bookmark-filled", "bookmark-outline", "bookmark-stack-filled",
        "bookmark-stack-outline", "bookmark-star-filled", "bookmark-star-outline", "bot-filled", "bot-outline",
        "bowtie-filled", "bowtie-outline", "box-filled", "box-open-filled", "box-open-outline", "box-outline",
        "breaking-news-filled", "breaking-news-outline", "briefcase-filled", "briefcase-outline",
        "browser-history-filled", "browser-history-outline", "browser-window-filled", "browser-window-outline",
        "brush-paint-filled", "brush-paint-outline", "brush-scale-filled", "brush-scale-outline", "bug-filled",
        "bug-outline", "building-bank-filled", "building-bank-outline", "building-city-filled",
        "building-city-outline", "building-heart-filled", "building-heart-outline", "building-high-school-filled",
        "building-high-school-outline", "building-school-filled", "building-school-outline", "bulb-filled",
        "bulb-outline", "bus-filled", "bus-outline", "butterfly-filled", "butterfly-outline", "cake-filled",
        "cake-outline", "calendar-add-filled", "calendar-add-outline", "calendar-blank-filled",
        "calendar-blank-outline", "calendar-filled", "calendar-going-filled", "calendar-going-outline",
        "calendar-list-bullet-filled", "calendar-list-bullet-outline", "calendar-maybe-filled",
        "calendar-maybe-outline", "calendar-outline", "calendar-star-filled", "calendar-star-outline",
        "camcorder-cross-filled", "camcorder-cross-outline", "camcorder-filled", "camcorder-incoming-filled",
        "camcorder-incoming-outline", "camcorder-live-filled", "camcorder-live-outline", "camcorder-outgoing-filled",
        "camcorder-outgoing-outline", "camcorder-outline", "camcorder-plus-filled", "camcorder-plus-outline",
        "camcorder-slash-filled", "camcorder-slash-outline", "camera-filled", "camera-outline",
        "camera-rotate-filled", "camera-rotate-outline", "campfire-filled", "campfire-outline",
        "candle-religion-filled", "candle-religion-outline", "car-filled", "car-outline", "car-wheel-filled",
        "car-wheel-outline", "card-horizontal-filled", "card-horizontal-outline", "card-person-filled",
        "card-person-outline", "card-stack-star-filled", "card-stack-star-outline", "cards-filled", "cards-outline",
        "cat-filled", "cat-outline", "categories-filled", "categories-outline", "caution-circle-filled",
        "caution-circle-outline", "caution-cloud-filled", "caution-cloud-outline", "caution-filled",
        "caution-octagon-filled", "caution-octagon-outline", "caution-outline", "caution-triangle-filled",
        "caution-triangle-outline", "changed-beliefs-filled", "changed-beliefs-outline", "checkmark-2-circle-filled",
        "checkmark-2-circle-outline", "checkmark-circle-filled", "checkmark-circle-outline", "checkmark-filled",
        "checkmark-outline", "checkmark-square-filled", "checkmark-square-outline", "chevron-double-left-filled",
        "chevron-double-left-outline", "chevron-double-right-filled", "chevron-double-right-outline",
        "chevron-down-circle-filled", "chevron-down-circle-outline", "chevron-down-filled", "chevron-down-outline",
        "chevron-left-circle-filled", "chevron-left-circle-outline", "chevron-left-filled", "chevron-left-outline",
        "chevron-right-circle-filled", "chevron-right-circle-outline", "chevron-right-filled",
        "chevron-right-outline", "chevron-up-circle-filled", "chevron-up-circle-outline", "chevron-up-filled",
        "chevron-up-outline", "chick-2-filled", "chick-2-outline", "chick-nest-filled", "chick-nest-outline",
        "circle-2-filled", "circle-2-outline", "circle-3-filled", "circle-3-outline", "circle-copyright-filled",
        "circle-copyright-outline", "circle-dot-active-filled", "circle-dot-active-outline",
        "circle-dot-notification-filled", "circle-dot-notification-outline", "circle-filled", "circle-full-filled",
        "circle-full-outline", "circle-halves-filled", "circle-halves-outline", "circle-heart-ribbon-filled",
        "circle-heart-ribbon-outline", "circle-outline", "circle-ribbon-star-filled", "circle-ribbon-star-outline",
        "circles-5-filled", "circles-5-outline", "circles-scale-filled", "circles-scale-left-right-filled",
        "circles-scale-left-right-outline", "circles-scale-outline", "clapper-open-filled", "clapper-open-outline",
        "clock-filled", "clock-outline", "closed-caption-filled", "closed-caption-outline",
        "closed-caption-slash-filled", "closed-caption-slash-outline", "cocktail-filled", "cocktail-outline",
        "code-filled", "code-outline", "coin-stack-filled", "coin-stack-outline", "columns-3-filled",
        "columns-3-outline", "comment-audio-hi-filled", "comment-audio-hi-outline", "comment-cross-filled",
        "comment-cross-outline", "comment-dots-filled", "comment-dots-outline", "comment-filled",
        "comment-lines-filled", "comment-lines-outline", "comment-off-filled", "comment-off-outline",
        "comment-outline", "comment-outline-20", "comment-photo-filled", "comment-photo-outline",
        "comment-play-filled", "comment-play-outline", "comment-questions-filled", "comment-questions-outline",
        "comment-shield-star-filled", "comment-shield-star-outline", "comment-slash-filled", "comment-slash-outline",
        "comment-star-filled", "comment-star-outline", "comment-swish-filled", "comment-swish-outline",
        "community-notes-filled", "community-notes-outline", "community-resources-filled", "community-resources-outline",
        "compass-filled", "compass-outline", "compose-filled", "compose-outline", "constrain-filled",
        "constrain-outline", "contact-filled", "contact-outline", "content-note-filled", "content-note-messages-filled",
        "content-note-messages-outline", "content-note-outline", "copy-filled", "copy-outline", "coupon-filled",
        "coupon-outline", "crafts-filled", "crafts-outline", "creative-formats-filled", "creative-formats-outline",
        "crop-filled", "crop-outline", "cross-circle-filled", "cross-circle-outline", "cross-filled",
        "cross-outline", "cup-filled", "cup-outline", "cupcake-filled", "cupcake-outline",
        "currency-thb-circle-filled", "currency-thb-circle-outline", "currency-usd-filled", "currency-usd-outline",
        "cursor-filled", "cursor-outline", "dashboard-filled", "dashboard-outline", "deli-sandwich-filled",
        "deli-sandwich-outline", "deskbell-filled", "deskbell-outline", "desktop-filled", "desktop-outline",
        "diagnosed-filled", "diagnosed-outline", "diamond-filled", "diamond-outline", "diamond-rise-filled",
        "diamond-rise-outline", "dice-filled", "dice-outline", "direct-filled", "direct-outline",
        "directions-filled", "directions-outline", "dishwasher-filled", "dishwasher-outline", "document-filled",
        "document-magnifying-glass-filled", "document-magnifying-glass-outline", "document-outline",
        "documents-filled", "documents-outline", "dog-filled", "dog-outline", "dollar-circle-filled",
        "dollar-circle-outline", "dot-1-filled", "dot-1-outline", "dots-2-horizontal-filled",
        "dots-2-horizontal-outline", "dots-3-circle-filled", "dots-3-circle-outline", "dots-3-horizontal",
        "dots-3-horizontal-filled", "dots-3-horizontal-outline", "dots-3-vertical-filled", "dots-3-vertical-outline",
        "download-circle-filled", "download-circle-outline", "download-filled", "download-outline", "draft-filled",
        "draft-outline", "drag-filled", "drag-outline", "dress-filled", "dress-outline", "dumbbell-filled",
        "dumbbell-outline", "duration-1-filled", "duration-1-outline", "duration-30-filled", "duration-30-outline",
        "duration-60-filled", "duration-60-outline", "duration-filled", "duration-outline", "edit-clip-filled",
        "edit-clip-outline", "edit-history-filled", "edit-history-outline", "egg-crack-filled", "egg-crack-outline",
        "egg-filled", "egg-outline", "elevator-filled", "elevator-outline", "emoji-filled", "emoji-outline",
        "envelope-dot-notifications-filled", "envelope-dot-notifications-outline", "envelope-filled",
        "envelope-invitation-filled", "envelope-invitation-outline", "envelope-open-filled", "envelope-open-outline",
        "envelope-outline", "equal-filled", "equal-outline", "eraser-filled", "eraser-outline", "explicit-filled",
        "explicit-outline", "eye-cross-filled", "eye-cross-outline", "eye-filled", "eye-outline",
        "eyebrows-filled", "eyebrows-outline", "face-happy-filled", "face-happy-outline", "face-laughing-filled",
        "face-laughing-outline", "face-meme-filled", "face-meme-outline", "face-neutral-filled",
        "face-neutral-outline", "face-sad-filled", "face-sad-outline", "face-sparkles-filled", "face-sparkles-outline",
        "face-very-happy-filled", "face-very-happy-outline", "face-very-unhappy-filled", "face-very-unhappy-outline",
        "facebook-page-filled", "facebook-page-outline", "feed-filled", "feed-outline", "feedback-filled",
        "feedback-outline", "feeds-filled", "feeds-outline", "film-filled", "film-outline", "film-projector-filled",
        "film-projector-outline", "film-stack-filled", "film-stack-outline", "filter-filled", "filter-outline",
        "filter-sliders-filled", "filter-sliders-outline", "first-aid-filled", "first-aid-outline", "flag-filled",
        "flag-outline", "flame-filled", "flame-outline", "flash-auto-filled", "flash-auto-outline",
        "flash-default-filled", "flash-default-outline", "flash-off-filled", "flash-off-outline",
        "flash-slash-filled", "flash-slash-outline", "flip-horizontal-a-filled", "flip-horizontal-a-outline",
        "folder-arrows-left-right-filled", "folder-arrows-left-right-outline", "folder-save-filled",
        "folder-save-outline", "follow-filled", "follow-outline", "following-filled", "following-outline",
        "football-filled", "football-outline", "fork-knife-filled", "fork-knife-outline", "frames-cross-filled",
        "frames-cross-outline", "frames-filled", "frames-outline", "friend-add-filled", "friend-add-outline",
        "friend-block-filled", "friend-block-outline", "friend-book-appointment-filled", "friend-book-appointment-outline",
        "friend-confirm-filled", "friend-confirm-outline", "friend-dot-active-filled", "friend-dot-active-outline",
        "friend-edit-filled", "friend-edit-outline", "friend-except-filled", "friend-except-outline",
        "friend-find-filled", "friend-find-outline", "friend-flag-filled", "friend-flag-outline",
        "friend-list-filled", "friend-list-outline", "friend-neutral-filled", "friend-neutral-outline",
        "friend-remove-filled", "friend-remove-outline", "friend-request-filled", "friend-request-outline",
        "friend-share-filled", "friend-share-outline", "friend-tag-filled", "friend-tag-outline",
        "friends-chrome-filled", "friends-chrome-outline", "friends-engagement-filled", "friends-engagement-outline",
        "friends-filled", "friends-outline", "friends-plus-filled", "friends-plus-outline", "fundraiser-filled",
        "fundraiser-outline", "funnel-chart-filled", "funnel-chart-outline", "game-controller-filled",
        "game-controller-outline", "gears-two-filled", "gears-two-outline", "gem-effects-filled",
        "gem-effects-outline", "gem-star-filled", "gem-star-outline", "gen-ai-brush-arts-filled",
        "gen-ai-brush-arts-outline", "gen-ai-bulb-filled", "gen-ai-bulb-outline", "gen-ai-consumer-filled",
        "gen-ai-consumer-outline", "gen-ai-face-filled", "gen-ai-face-outline", "gen-ai-film-reel-filled",
        "gen-ai-film-reel-outline", "gen-ai-imagine-filled", "gen-ai-imagine-outline", "gen-ai-magnifying-glass-filled",
        "gen-ai-magnifying-glass-outline", "gen-ai-memory-filled", "gen-ai-memory-outline", "gen-ai-music-list-filled",
        "gen-ai-music-list-outline", "gen-ai-pencil-filled", "gen-ai-pencil-outline", "gen-ai-photo-square-filled",
        "gen-ai-photo-square-outline", "gen-ai-play-circle-filled", "gen-ai-play-circle-outline",
        "gen-ai-plus-square-filled", "gen-ai-plus-square-outline", "gen-ai-profile-filled", "gen-ai-profile-outline",
        "gen-ai-send-filled", "gen-ai-send-outline", "gen-ai-star-filled", "gen-ai-star-outline",
        "gen-ai-stickers-filled", "gen-ai-stickers-outline", "gen-ai-studio-filled", "gen-ai-studio-outline",
        "gen-ai-text-background-filled", "gen-ai-text-background-outline", "gen-ai-translate-filled",
        "gen-ai-translate-outline", "gif-filled", "gif-outline", "gift-box-star-filled", "gift-box-star-outline",
        "gift-card-filled", "gift-card-outline", "globe-americas-12", "globe-americas-filled", "globe-americas-outline",
        "globe-generic-filled", "globe-generic-outline", "go-to-filled", "go-to-outline", "google-cast-filled",
        "google-cast-on-filled", "google-cast-on-outline", "google-cast-outline", "gramophone-filled",
        "gramophone-outline", "green-screen-filled", "green-screen-outline", "grid-4-filled", "grid-4-outline",
        "grid-9-circle-filled", "grid-9-circle-outline", "grid-9-filled", "grid-9-outline", "group-checkmark-filled",
        "group-checkmark-outline", "group-filled", "group-outline", "group-plus-filled", "group-plus-outline",
        "guitar-filled", "guitar-outline", "gyroscope-cross-filled", "gyroscope-cross-outline", "gyroscope-filled",
        "gyroscope-outline", "hand-badge-checkmark-filled", "hand-badge-checkmark-outline", "hand-chat-bubble-filled",
        "hand-chat-bubble-outline", "hand-coin-filled", "hand-coin-outline", "hand-gift-box-filled",
        "hand-gift-box-outline", "hand-soap-filled", "hand-soap-outline", "hand-thumbs-down-filled",
        "hand-thumbs-down-outline", "hand-thumbs-up-down-filled", "hand-thumbs-up-down-outline",
        "hand-thumbs-up-filled", "hand-thumbs-up-outline", "hashtag-filled", "hashtag-outline", "hd-filled",
        "hd-outline", "headphones-filled", "headphones-outline", "health-filled", "health-outline",
        "heart-filled", "heart-outline", "heart-pulse-filled", "heart-pulse-outline", "heart-slash-filled",
        "heart-slash-outline", "heart-support-filled", "heart-support-outline", "height-filled", "height-outline",
        "hex-star-filled", "hex-star-outline", "hide-filled", "hide-outline", "high-five-hands-filled",
        "high-five-hands-outline", "hourglass-filled", "hourglass-outline", "house-dollar-filled",
        "house-dollar-outline", "house-filled", "house-outline", "hub-filled", "hub-outline", "inbox-filled",
        "inbox-outline", "info-circle-filled", "info-circle-outline", "info-cursive-filled", "info-cursive-outline",
        "info-filled", "info-outline", "instagram-boomerang-filled", "instagram-boomerang-outline",
        "instagram-layout-1-and-2-filled", "instagram-layout-1-and-2-outline", "instagram-layout-2-horiz-filled",
        "instagram-layout-2-horiz-outline", "instagram-layout-2-vert-filled", "instagram-layout-2-vert-outline",
        "instagram-layout-3-horiz-filled", "instagram-layout-3-horiz-outline", "instagram-layout-4-grid-filled",
        "instagram-layout-4-grid-outline", "instagram-layout-6-grid-filled", "instagram-layout-6-grid-outline",
        "instagram-layout-filled", "instagram-layout-outline", "instagram-new-story-filled", "instagram-new-story-outline",
        "instagram-story-filled", "instagram-story-outline", "internet-filled", "internet-outline", "key-filled",
        "key-house-filled", "key-house-outline", "key-outline", "keyboard-filled", "keyboard-outline",
        "keyhole-circle-filled", "keyhole-circle-outline", "kids-filled", "kids-outline", "landscape-view-filled",
        "landscape-view-outline", "language-filled", "language-outline", "laptop-filled", "laptop-outline",
        "leaf-filled", "leaf-outline", "leave-filled", "leave-outline", "license-filled", "license-outline",
        "life-event-filled", "life-event-major-filled", "life-event-major-outline", "life-event-outline",
        "life-preserver-filled", "life-preserver-outline", "like-filled", "like-filled-20", "like-outline",
        "like-outline-20", "line-bounce-filled", "line-bounce-outline", "line-chart-down-filled",
        "line-chart-down-outline", "line-chart-filled", "line-chart-outline", "line-smooth-filled",
        "line-smooth-outline", "link", "link-filled", "link-outline", "list-arrow-down-filled",
        "list-arrow-down-outline", "list-arrow-up-filled", "list-arrow-up-outline", "list-bullet-filled",
        "list-bullet-outline", "list-gear-filled", "list-gear-outline", "list-numbered-filled",
        "list-numbered-outline", "live-filled", "live-outline", "live-person-filled", "live-person-outline",
        "live-photos-on-filled", "live-photos-on-outline", "local-news-filled", "local-news-outline",
        "location-filled", "location-outline", "lotus-filled", "lotus-outline", "magic-wand-filled",
        "magic-wand-outline", "magnifying-glass-filled", "magnifying-glass-outline", "map-filled", "map-outline",
        "marketplace-arrow-right-filled", "marketplace-arrow-right-outline", "marketplace-filled", "marketplace-outline",
        "masks-filled", "masks-outline", "media-rising-filled", "media-rising-outline", "media-stack-filled",
        "media-stack-outline", "megaphone-filled", "megaphone-lines-filled", "megaphone-lines-outline",
        "megaphone-outline", "mentorship-filled", "mentorship-outline", "messages-filled", "messages-outline",
        "messages-question-filled", "messages-question-outline", "messages-spotlight-filled", "messages-spotlight-outline",
        "messenger-breaking-news-filled", "messenger-breaking-news-outline", "microphone-cross-filled",
        "microphone-cross-outline", "microphone-effects-filled", "microphone-effects-outline", "microphone-filled",
        "microphone-karaoke-filled", "microphone-karaoke-outline", "microphone-outline", "microphone-retro-filled",
        "microphone-retro-outline", "microphone-slash-filled", "microphone-slash-outline", "microwave-filled",
        "microwave-outline", "military-land-filled", "military-land-outline", "miniplayer-filled", "miniplayer-outline",
        "minus-circle-filled", "minus-circle-outline", "minus-filled", "minus-outline", "minus-square-filled",
        "minus-square-outline", "mobile-filled", "mobile-install-filled", "mobile-install-outline", "mobile-outline",
        "monetary-gift-box-filled", "monetary-gift-box-outline", "monetary-star-filled", "monetary-star-outline",
        "moon-filled", "moon-outline", "more-filled", "more-outline", "more-shapes-filled", "more-shapes-outline",
        "mortar-board-filled", "mortar-board-outline", "motorcycle-filled", "motorcycle-outline", "music-effects-filled",
        "music-effects-outline", "music-filled", "music-list-filled", "music-list-outline", "music-outline",
        "nav-cross", "nav-cross-filled", "nav-cross-outline", "navicon-sub-filled", "navicon-sub-outline",
        "nearby-places-filled", "nearby-places-outline", "necklace-filled", "necklace-outline", "neighborhood-filled",
        "neighborhood-outline", "network-filled", "network-outline", "news-feed-clock-filled", "news-feed-clock-outline",
        "news-feed-filled", "news-feed-headlines-filled", "news-feed-headlines-outline", "news-feed-home-filled",
        "news-feed-home-outline", "news-feed-outline", "next-filled", "next-outline", "note-add-filled",
        "note-add-outline", "note-filled", "note-outline", "notifications-cross-filled", "notifications-cross-outline",
        "notifications-filled", "notifications-outline", "notifications-ring-filled", "notifications-ring-outline",
        "offers-filled", "offers-outline", "on-this-day-filled", "on-this-day-outline", "oven-filled",
        "oven-outline", "overlapping-papers-filled", "overlapping-papers-outline", "owl-filled", "owl-outline",
        "pacifier-filled", "pacifier-outline", "palette-filled", "palette-outline", "paper-clip-filled",
        "paper-clip-outline", "paper-fold-filled", "paper-fold-outline", "paper-fold-text-filled",
        "paper-fold-text-outline", "paper-stack-filled", "paper-stack-outline", "party-hat-filled", "party-hat-outline",
        "passport-chip-filled", "passport-chip-outline", "pause-circle-filled", "pause-circle-outline", "pause-filled",
        "pause-outline", "paw-filled", "paw-outline", "pencil-checkmark-filled", "pencil-checkmark-outline",
        "pencil-filled", "pencil-outline", "pencil-underline-filled", "pencil-underline-outline", "pentagon-heart-filled",
        "pentagon-heart-outline", "phone-cross-filled", "phone-cross-outline", "phone-end-filled", "phone-end-outline",
        "phone-filled", "phone-incoming-filled", "phone-incoming-outline", "phone-outgoing-filled",
        "phone-outgoing-outline", "phone-outline", "photo-add-filled", "photo-add-outline", "photo-album-filled",
        "photo-album-outline", "photo-blank-filled", "photo-blank-outline", "photo-collage-filled",
        "photo-collage-outline", "photo-download-filled", "photo-download-outline", "photo-filled", "photo-heart-filled",
        "photo-heart-outline", "photo-outline", "photo-remix-filled", "photo-remix-outline", "photo-remove-filled",
        "photo-remove-outline", "photo-square-filled", "photo-square-outline", "pie-chart-filled", "pie-chart-outline",
        "pin-checkmark-filled", "pin-checkmark-outline", "pin-cross-filled", "pin-cross-outline", "pin-filled",
        "pin-location-filled", "pin-location-outline", "pin-outline", "pin-star-filled", "pin-star-outline",
        "play-circle-filled", "play-circle-outline", "play-filled", "play-list-filled", "play-list-outline",
        "play-outline", "plus-circle", "plus-circle-filled", "plus-circle-outline", "plus-filled", "plus-outline",
        "plus-square-filled", "plus-square-outline", "point-filled", "point-outline", "poke-checkmark-filled",
        "poke-checkmark-outline", "poke-filled", "poke-outline", "politics-filled", "politics-outline",
        "poll-filled", "poll-outline", "polls-filled", "polls-outline", "pop-filled", "pop-outline",
        "portrait-view-filled", "portrait-view-outline", "post-checkmark-filled", "post-checkmark-outline",
        "post-clock-filled", "post-clock-outline", "post-filled", "post-outline", "post-slash-filled",
        "post-slash-outline", "posts-filled", "posts-outline", "praying-hands-filled", "praying-hands-open-filled",
        "praying-hands-open-outline", "praying-hands-outline", "previous-filled", "previous-outline", "privacy-filled",
        "privacy-outline", "privacy-settings-filled", "privacy-settings-outline", "privacy-unlocked-filled",
        "privacy-unlocked-outline", "professional-dashboard-filled", "professional-dashboard-outline",
        "profile-checkmark-filled", "profile-checkmark-outline", "profile-cover-photo-filled", "profile-cover-photo-outline",
        "profile-facebook-filled", "profile-facebook-outline", "profile-filled", "profile-gem-filled",
        "profile-gem-outline", "profile-media-review-filled", "profile-media-review-outline", "profile-outline",
        "profile-professional-filled", "profile-professional-outline", "profile-rounded-square-filled",
        "profile-rounded-square-outline", "profile-settings-filled", "profile-settings-outline", "profile-slash-filled",
        "profile-slash-outline", "protractor-filled", "protractor-outline", "push-notifications-filled",
        "push-notifications-outline", "push-notifications-slash-filled", "push-notifications-slash-outline",
        "pushpin-filled", "pushpin-outline", "pushpin-slash-filled", "pushpin-slash-outline", "qr-code-filled",
        "qr-code-outline", "qr-scanner-filled", "qr-scanner-outline", "question-circle-filled", "question-circle-outline",
        "question-filled", "question-outline", "quit-clock-filled", "quit-clock-outline", "quit-filled",
        "quit-outline", "quotes-filled", "quotes-outline", "ratio-vertical-filled", "ratio-vertical-outline",
        "reaction-counts-filled", "reaction-counts-outline", "recents-filled", "recents-outline", "redo-filled",
        "redo-outline", "refresh-left-filled", "refresh-left-outline", "refresh-right-filled", "refresh-right-outline",
        "refrigerator-filled", "refrigerator-outline", "relationship-filled", "relationship-outline", "repeat-1-filled",
        "repeat-1-outline", "repeat-filled", "repeat-outline", "reply-filled", "reply-outline", "report-filled",
        "report-outline", "reshare-filled", "reshare-outline", "resize-down-filled", "resize-down-outline",
        "resize-exit-filled", "resize-exit-outline", "resize-free-filled", "resize-free-outline", "resize-up-filled",
        "resize-up-outline", "ribbon-filled", "ribbon-outline", "road-filled", "road-outline", "robot-filled",
        "robot-outline", "rocket-filled", "rocket-outline", "roofing-filled", "roofing-outline", "rotate-cw-filled",
        "rotate-cw-outline", "rotate-filled", "rotate-image-filled", "rotate-image-outline", "rotate-outline",
        "rotate-view-filled", "rotate-view-outline", "rows-3-filled", "rows-3-outline", "royalty-free-filled",
        "royalty-free-outline", "ruler-filled", "ruler-outline", "running-filled", "running-outline", "rv-filled",
        "rv-outline", "safety-check-filled", "safety-check-outline", "sample-hi-filled", "sample-hi-outline",
        "sample-lo-filled", "sample-lo-outline", "sample-mid-filled", "sample-mid-outline", "scale-filled",
        "scale-outline", "scissors-filled", "scissors-outline", "screen-dual-filled", "screen-dual-outline",
        "screen-dual-plus-filled", "screen-dual-plus-outline", "screen-share-mobile-filled", "screen-share-mobile-outline",
        "send-filled", "send-outline", "server-timeout-filled", "server-timeout-outline", "settings-filled",
        "settings-outline", "share-android-filled", "share-android-outline", "share-external-filled",
        "share-external-outline", "share-filled", "share-ios-filled", "share-ios-outline", "share-outline",
        "share-outline-20", "share-stack-filled", "share-stack-outline", "shield-checkmark-filled",
        "shield-checkmark-outline", "shield-content-filled", "shield-content-outline", "shield-filled",
        "shield-health-filled", "shield-health-outline", "shield-keyhole-filled", "shield-keyhole-outline",
        "shield-outline", "shield-person-filled", "shield-person-outline", "shield-star-filled", "shield-star-outline",
        "shopping-bag-filled", "shopping-bag-outline", "shopping-cart-filled", "shopping-cart-outline",
        "shopping-cart-plus-filled", "shopping-cart-plus-outline", "shops-filled", "shops-outline",
        "sidebar-down-blank-filled", "sidebar-down-blank-outline", "sidebar-filled", "sidebar-left-close-filled",
        "sidebar-left-close-outline", "sidebar-left-open-filled", "sidebar-left-open-outline", "sidebar-outline",
        "sidebar-right-blank-filled", "sidebar-right-blank-outline", "sidebar-right-close-filled",
        "sidebar-right-close-outline", "sidebar-right-filled", "sidebar-right-open-filled", "sidebar-right-open-outline",
        "sidebar-right-outline", "sidebar-top-blank-filled", "sidebar-top-blank-outline", "signal-tower-filled",
        "signal-tower-outline", "sim-card-filled", "sim-card-outline", "skip-backward-10-filled",
        "skip-backward-10-outline", "skip-backward-30-filled", "skip-backward-30-outline", "skip-backward-5-filled",
        "skip-backward-5-outline", "skip-forward-10-filled", "skip-forward-10-outline", "skip-forward-30-filled",
        "skip-forward-30-outline", "skip-forward-5-filled", "skip-forward-5-outline", "slash-circle-filled",
        "slash-circle-outline", "slash-filled", "slash-outline", "smart-glasses-filled", "smart-glasses-outline",
        "snow-globe-filled", "snow-globe-outline", "soccer-filled", "soccer-outline", "soup-filled", "soup-outline",
        "spas-filled", "spas-outline", "sponsored-filled", "sponsored-outline", "spray-can-filled", "spray-can-outline",
        "sprout-filled", "sprout-outline", "square-corner-bottom-left-box-filled", "square-corner-bottom-left-box-outline",
        "square-corner-bottom-right-box-filled", "square-corner-bottom-right-box-outline", "square-corner-top-left-box-filled",
        "square-corner-top-left-box-outline", "square-corner-top-right-box-filled", "square-corner-top-right-box-outline",
        "square-dashed-filled", "square-dashed-outline", "square-filled", "square-outline", "squares-2-filled",
        "squares-2-outline", "squiggle-filled", "squiggle-outline", "star-circle-filled", "star-circle-outline",
        "star-cross-filled", "star-cross-outline", "star-filled", "star-half-filled", "star-outline",
        "star-prize-filled", "star-prize-outline", "star-reviews-filled", "star-reviews-outline", "star-slash-filled",
        "star-slash-outline", "star-tip-filled", "star-tip-outline", "star-with-face-filled", "star-with-face-outline",
        "steering-wheel-filled", "steering-wheel-outline", "stickers-filled", "stickers-outline", "stop-filled",
        "stop-outline", "stop-playback-filled", "stop-playback-outline", "stopwatch-filled", "stopwatch-outline",
        "store-filled", "store-outline", "store-sign-heart-filled", "store-sign-heart-outline", "store-visits-filled",
        "store-visits-outline", "stories-archive-filled", "stories-archive-outline", "stories-filled", "stories-outline",
        "stroller-filled", "stroller-outline", "style-effects-filled", "style-effects-outline", "subgroup-messenger-private-filled",
        "subgroup-messenger-private-open-filled", "subgroup-messenger-private-open-outline", "subgroup-messenger-private-outline",
        "subgroup-messenger-public-filled", "subgroup-messenger-public-outline", "suicide-prevention-filled",
        "suicide-prevention-outline", "sun-with-clouds-filled", "sun-with-clouds-outline", "sunrise-filled",
        "sunrise-outline", "t-shirt-filled", "t-shirt-heart-filled", "t-shirt-heart-outline", "t-shirt-outline",
        "tag-filled", "tag-outline", "tag-price-filled", "tag-price-outline", "tag-remove-filled", "tag-remove-outline",
        "tag-stack-filled", "tag-stack-outline", "tag-star-filled", "tag-star-outline", "takeout-box-filled",
        "takeout-box-outline", "target-filled", "target-outline", "test-arrow-down-vote-filled", "test-arrow-down-vote-outline",
        "test-arrow-up-vote-filled", "test-arrow-up-vote-outline", "test-profile-rounded-square-checkmark-circle-filled",
        "test-profile-rounded-square-checkmark-circle-outline", "text-align-center-filled", "text-align-center-outline",
        "text-align-left-filled", "text-align-left-outline", "text-align-right-filled", "text-align-right-outline",
        "text-animation-filled", "text-animation-outline", "text-cursor-filled", "text-cursor-outline", "text-filled",
        "text-indent-decrease-filled", "text-indent-decrease-outline", "text-indent-increase-filled",
        "text-indent-increase-outline", "text-outline", "text-resize-filled", "text-resize-outline", "text-square-filled",
        "text-square-outline", "thermostat-filled", "thermostat-outline", "thought-bubble-filled", "thought-bubble-outline",
        "ticket-filled", "ticket-outline", "toggle-filled", "toggle-outline", "toolbox-filled", "toolbox-outline",
        "tools-filled", "tools-outline", "topics-filled", "topics-outline", "trailer-filled", "trailer-outline",
        "translate-filled", "translate-outline", "transmission-filled", "transmission-outline", "trash-filled",
        "trash-outline", "treasure-chest-filled", "treasure-chest-outline", "tree-filled", "tree-outline",
        "trending-arrow-down-filled", "trending-arrow-down-outline", "trending-arrow-filled", "trending-arrow-outline",
        "trending-filled", "trending-outline", "triangle-down-filled", "triangle-down-outline", "triangle-left-filled",
        "triangle-left-outline", "triangle-right-filled", "triangle-right-outline", "triangle-up-filled",
        "triangle-up-outline", "trim-filled", "trim-outline", "trophy-filled", "trophy-outline", "trophy-star-filled",
        "trophy-star-outline", "trowel-filled", "trowel-outline", "truck-shipping-filled", "truck-shipping-outline",
        "tv-filled", "tv-outline", "undo-filled", "undo-outline", "unfollow-filled", "unfollow-outline",
        "unlink-filled", "unlink-outline", "upload-filled", "upload-outline", "venn-diagram-2-filled",
        "venn-diagram-2-outline", "video-filled", "video-outline", "viewfinder-magnifying-glass-filled",
        "viewfinder-magnifying-glass-outline", "vinyl-filled", "vinyl-outline", "vote-filled", "vote-outline",
        "walk-filled", "walk-outline", "washing-machine-filled", "washing-machine-outline", "watch-tv",
        "watch-tv-filled", "watch-tv-outline", "water-filled", "water-outline", "water-slash-filled",
        "water-slash-outline", "waving-hand-filled", "waving-hand-outline", "weather-bolt-filled", "weather-bolt-outline",
        "weather-cloud-filled", "weather-cloud-outline", "wireless-filled", "wireless-outline", "wireless-slash-filled",
        "wireless-slash-outline", "wrench-filled", "wrench-outline", "zoom-in-filled", "zoom-in-outline",
        "zoom-out-filled", "zoom-out-outline"
    ]
}

// MARK: - Icons Preview View
struct IconsPreviewView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var searchText = ""
    
    private let columns = [
        GridItem(.adaptive(minimum: 100), spacing: 8, alignment: .top)
    ]
    
    private var filteredIcons: [String] {
        if searchText.isEmpty {
            return Image.allIconNames
        } else {
            return Image.allIconNames.filter { $0.localizedCaseInsensitiveContains(searchText) }
        }
    }
    
    var body: some View {
        VStack(spacing: 0) {
            FDSNavigationBarCentered(
                title: "Icons",
                backAction: { dismiss() }
            )
            
            ScrollView {
                LazyVGrid(columns: columns, spacing: 12) {
                    ForEach(filteredIcons, id: \.self) { iconName in
                        IconCard(iconName: iconName)
                    }
                }
                .padding(.horizontal, 16)
                .padding(.top, 12)
            }
            .background(Color("surfaceBackground"))
        }
    }
}

// MARK: - Icon Card Component
struct IconCard: View {
    let iconName: String
    
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            // Icon display
            Rectangle()
                .fill(Color("webWash"))
                .frame(height: 72)
                .overlay(
                    Image(iconName)
                        .resizable()
                        .renderingMode(.template)
                        .foregroundStyle(Color("primaryIcon"))
                        .aspectRatio(contentMode: .fit)
                        .frame(width: 24, height: 24)
                )
                .cornerRadius(12)
            
            // Icon name
            VStack(alignment: .center, spacing: 0) {
                Text(iconName)
                    .meta4LinkTypography()
                    .foregroundStyle(Color("primaryText"))
                    .lineLimit(2)
                    .multilineTextAlignment(.center)
                    .frame(maxWidth: .infinity)
                
            }
        }
    }
}

// MARK: - Preview
#Preview {
    IconsPreviewView()
}
